version: 2.1

jobs:
  vue-build:
    docker:
      - image: cimg/node:16.17
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Vue Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  docker-build-and-push:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/frontend:$TAG .
      - run:
          name: Push Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/frontend:$TAG

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - vue-build
      - docker-build-and-push:
          requires:
            - vue-build
